sudo: false
dist: trusty
language: node_js
node_js:
 - "node"
 - "6"

notifications:
  slack:
    secure: woazEreA6IXu9c2Lirri8ZeSfIqZcnOfL+hOi21u06IeQHOcDdW1bnvihvLwTxSSDMgEwX5NJWlblaoPX32HOyWLMEDAldwJjv6kU+kfGWJy8eJCcn2VNcEcVr6oh0LWCbQ4PIjf2A6jh/FHaVm/tEA7HhfGlMrVWyqRUQc8pLdY1yQI6yFUQ/vO41ZNXW5INMcAO0WSQOfh9dw64T8/PhwY+mPddN80urB0z1XOenCQS3S80zdPkPNQVmuJrsJR2H/jcU3ea0BvMZKVuzIFl5YSoeuhNPPdCh7AX6bpWcVPRjJ/UfT3b4MhGABjTj+SQbF1zEFoDZnuTgpuGA/QG1YoLL4SCDbJC0rP620EsmUpZ4ezIZo4R+YGJ0oiVGYq1NeVfrrO4K6ix/U4kUR9cnkfMxFwLhzy8k69ipUlmcFFbf4WsBqcdnMTBje27AazYZlIIlOVxxR6T4dIw36oQ67kcZ1iHvT0iOdh1IC2XijkAuQo8VdMd7Nfaaa8zIbQ2hU/0E4kv4HFIRsWIlr7O3RJZVF4O0Fs9aWvpMHEeUNVHAyZM58uG4f6UdHncftUHicsjsxzjvCkXGq4Gcti4RhFBptSSnwCLOnFugX0M0xhxLrn5r0lctK+plzKrYogcWSh9RDcHPnaYaF/cwS6QjMdGcU4zUIKJ7c2bJoRBSM=
cache:
  directories:
  - "node_modules"

install:
 - npm install coveralls
 - npm install

script:
 - npm run lint
 - npm run build
 - npm run coverage

after_success:
 - npm run coveralls
