#!/usr/bin/env sh
if [ ! -z $npm_config_production ]; then
    exit
fi

echo "[GitHooks] Copying Git Hooks"
cp githooks/commit-msg.sh .git/hooks/commit-msg
cp githooks/post-checkout.sh .git/hooks/post-checkout
echo "[GitHooks] Done"
echo
